# Generated by Django 5.0.6 on 2024-06-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_time_order_created_at_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
